INSERT IGNORE INTO role(id, name) VALUES(1,'ROLE_USER');
INSERT IGNORE INTO role(id, name) VALUES(2,'ROLE_ADMIN');
INSERT IGNORE INTO role(id, name) VALUES(3,'ROLE_WORKER');

INSERT IGNORE INTO role(id, name) VALUES(1,'STATEMENT');
INSERT IGNORE INTO role(id, name) VALUES(2,'OPEN');
INSERT IGNORE INTO role(id, name) VALUES(3,'PREORDER');
INSERT IGNORE INTO role(id, name) VALUES(3,'WORK');
INSERT IGNORE INTO role(id, name) VALUES(3,'ARHIVE');