INSERT INTO role(id, name) VALUES(1,'ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO role(id, name) VALUES(2,'ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO role(id, name) VALUES(3,'ROLE_WORKER') ON CONFLICT DO NOTHING;
INSERT INTO role(id, name) VALUES(4,'ROLE_MANAGER') ON CONFLICT DO NOTHING;

INSERT INTO status(id, name) VALUES(1,'CREATED') ON CONFLICT DO NOTHING;
INSERT INTO status(id, name) VALUES(2,'ON TENDER') ON CONFLICT DO NOTHING;
INSERT INTO status(id, name) VALUES(3,'PREORDER') ON CONFLICT DO NOTHING;
INSERT INTO status(id, name) VALUES(4,'IN WORK') ON CONFLICT DO NOTHING;
INSERT INTO status(id, name) VALUES(5,'DONE') ON CONFLICT DO NOTHING;

INSERT INTO my_users(id, username, password) VALUES (1,'admin','$2a$10$7kQ1nv74qr7CiGAouEzxUOqoD9Pylh7nKY6WXDzAV6O1IF5R21tz.') ON CONFLICT DO NOTHING;
INSERT INTO user_role(user_id, role_id) VALUE (1,2) ON CONFLICT DO NOTHING;
